version: 2

before:
  hooks:
    - sh -c "cd lambda && go mod tidy"

builds:
  - id: webhook
    dir: lambda
    main: ./cmd/webhook
    binary: bootstrap
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64

  - id: scaleup
    dir: lambda
    main: ./cmd/scaleup
    binary: bootstrap
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64

  - id: scaledown
    dir: lambda
    main: ./cmd/scaledown
    binary: bootstrap
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: webhook-zip
    ids:
      - webhook
    formats:
      - zip
    name_template: >-
      webhook-{{ .Os }}-{{ .Arch }}
    strip_binary_directory: true
    wrap_in_directory: false

  - id: scaleup-zip
    ids:
      - scaleup
    formats:
      - zip
    name_template: >-
      scaleup-{{ .Os }}-{{ .Arch }}
    strip_binary_directory: true
    wrap_in_directory: false

  - id: scaledown-zip
    ids:
      - scaledown
    formats:
      - zip
    name_template: >-
      scaledown-{{ .Os }}-{{ .Arch }}
    strip_binary_directory: true
    wrap_in_directory: false

checksum:
  name_template: checksums.txt

release:
  footer: |
    **Full Changelog**: https://github.com/{{ .Env.GORELEASER_CURRENT_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  use: github-native
